name: Publish to Hex

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

jobs:
  publish:
    name: Build and Publish to Hex
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Elixir
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 'latest' # Specify version or use 'latest'
          otp-version: 'latest'    # Specify version or use 'latest'

      # Install dependencies
      - name: Install dependencies
        run: mix deps.get

      # Compile the project
      - name: Compile project
        run: mix compile

      # Publish to Hex
      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix hex.publish --yes
